spring:
  datasource:
    primarydatasource :
      driver-class-name: com.mysql.cj.jdbc.Driver
      url : jdbc:mysql://8.3.29.210:3306/testDb?useUnicode=true&characterEncoding=utf-8
      username: jldb
      password: Jldb$1234
      type: org.apache.commons.dbcp.BasicDataSource
    seconddatasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.3.29.210:3306/testDb2?useUnicode=true&characterEncoding=utf-8
      username: jldb
      password: Jldb$1234
      type: org.apache.commons.dbcp.BasicDataSource